### ISSUE TITLE
[QUESTION] How to update outdated packages?

### ISSUE THREAD

**Issue by KnorpelSenf** [pikapkg/cdn#101]
https://www.npmjs.com/package/typegram has its last publish six days ago and skypack still did not pick up the new version. I searched through all of your docs but could not find anything about the following two points.

1. How often does Skypack pull in new packages?
2. Is there a way to force refresh packages manually so a new version becomes available on Skypack?

**Comment by drwpow** [comment]
Hey, thanks so much for your question. We should probably clarify this on the docs, but right now, `www.skypack.dev` (the catalog) and `cdn.skypack.dev` are a little different.

The former is our “metadata” about a package, and sometimes that falls behind npm (usually because npm’s notifier hangs up). That’s probably what you’re referring to. I’m restarting it now and making sure it’s up-to-date.

The latter, though, is always up-to-date. If you visit `https://cdn.skypack.dev/typegram` you’ll see that matches the latest version from npm (`3.1.3`).

So as soon as you publish to npm, you can serve your package from `cdn.skypack.dev` (but note that on the very first request it may be a little slow as we prepare the package for the first time; after that first hit though it’ll be served instantly). And know that our metadata catalog may be a little slower to reflect changes.

Hopefully this helps!

**Comment by KnorpelSenf** [comment]
That is really cool, thank you so much!

**Comment by drwpow** [comment]
Update: just updated the docs here: https://app.gitbook.com/@skypack/s/skypack/troubleshooting-and-faq. Hopefully this is a little clearer than it was before.

**Comment by KnorpelSenf** [comment]
I'm getting a 404 for the link, but I read the FAQ and it's pretty clear there now. Thanks!

https://docs.skypack.dev/troubleshooting-and-faq#q-why-is-my-package-missing-or-outdated-on-skypack-dev
