### ISSUE TITLE
Hacker UI

### ISSUE THREAD

**Issue by chriscoyier** [pikapkg/cdn#103]
I saw in Louis Lazaris tools newsletter that Hacker UI was the most-clicked-on thing.
https://www.impressivewebs.com/most-interesting-front-end-developer-tools-2021/

https://hacker-ui.com/

I'm trying to use one of their demos, through SkyPack, on CodePen:
https://codepen.io/chriscoyier/pen/VwKxxqK?editors=0010

But it doesn't wanna go. I don't actually know if this is a problem with Skypack or not, but maybe? (Feel free to close if it's their problem)

**Comment by FredKSchott** [comment]
Hey Chris! I think the package doesn't yet support React 17, I followed up with the package author to confirm: https://github.com/hui-org/hacker-ui/issues/100

**Comment by FredKSchott** [comment]
Author responded in that thread, seems to be a React 17 issue (or may be related to project's beta status).

Because React 16 won't play well with other versions of React, we currently pin all versions of React to v17 regardless of the peerDependencies set by the package. This is a restriction that will only affect <=v16 React packages going forward.

Closing this for now since there's nothing for us to do on our end.

**Comment by chriscoyier** [comment]
Doesn't work at React 15 either...
https://codepen.io/chriscoyier/pen/VwKxxqK?editors=0010

Oh well, when the author is literally like "don't use this library", that's probably a good indication to not use the library.

**Comment by drwpow** [comment]
> Oh well, when the author is literally like "don't use this library", that's probably a good indication to not use the library.

Wise words 😄
