### ISSUE TITLE
[deno][react-dom] "stream" no dependency version info found

### ISSUE THREAD

**Issue by ynwd** [pikapkg/cdn#120]
```ts
import ReactDOMServer from "https://cdn.skypack.dev/react-dom/server";
```
Error:
```
error: Uncaught Error: [Package Error] "stream" no dependency version info found. (Imported by "react-dom").
throw new Error("[Package Error] \"stream\" no dependency version info found. (Imported by \"react-dom\").");
      ^
    at https://cdn.skypack.dev/error/unknown:stream?from=react-dom:13:7
```

**Comment by ynwd** [comment]
related issue: https://github.com/skypackjs/skypack-cdn/issues/42

**Comment by drwpow** [comment]
Yup this is the same as #42. Investigated this a little more, and I think we need to come up with a better solution for Deno. As stated in #42, one issue is that we leave the import as `'stream'` rather than `'node:stream'`.

We should change this, however, even if we did, it’d become a cryptic error in JS: ` error loading dynamically imported module`. So we almost need to come up with some sort of alternate mode so we serve `node:stream` to Deno, and a clear JS error to browsers. I’ll add that to our roadmap.

**Comment by drwpow** [comment]
Update: we now polyfill `stream` for the Deno client! If you blow away your Deno cache, please try again and it should load Deno‘s polyfilled `stream` instead, but only for Deno. Please give it a try and let me know if you have any issues.

**Comment by harleylang** [comment]
Thanks so much @drwpow !! The package appears to load without the aforementioned error. I'm catching a new issue when I try to import the package, I'll open a new ticket.
