### ISSUE TITLE
react@16 gives me 17

### ISSUE THREAD

**Issue by fonsp** [pikapkg/cdn#123]
The syntax `https://cdn.skypack.dev/react@16` seems to be broken, the version is ignored and i always get the latest version:

https://user-images.githubusercontent.com/6933510/106811555-c99edf00-666e-11eb-8e06-8561ae3130b6.mov

**Comment by FredKSchott** [comment]
That is correct: this is the one weird bit that we have to do for React: all versions of React from <v16 are hard-coded to v17.0.x

The reason is that React v16 doesn't support multiple versions of React on the same page. Because many users are already on React 17 and many packages have already made the switch to support v17 in their `peerDependency` version, this mismatch can cause issues if React 16 & 17 were ever to both load on the same page.

In future versions of React, this won't be an issue. And we're currently working on ways to let you pin the version of React that you'd like across all dependencies.

**Comment by fonsp** [comment]
Alright, sounds like you're on top of it! Thanks
