### ISSUE TITLE
snabbdom build error

### ISSUE THREAD

**Issue by mreinstein** [pikapkg/cdn#125]
hello!

I'm seeing this error when I attempt to `import snabbdom from 'https://cdn.skypack.dev/snabbdom'`:

```javascript
"snabbdom@v2.1.0" could not be built. 
Installing package...
No "exports" main resolved in snabbdom/package.json
No "exports" main resolved in /tmp/cdn/_H6UYsRNqAq21GxNPoCSl/node_modules/snabbdom/package.json
```

snabbdom's `package.json` module lacks a `main` field, but it does include `exports`:

https://github.com/snabbdom/snabbdom/blob/master/package.json#L6-L25

Is this a problem with skypack not being able to parse a legit module, or is snabbdom missing something in it's `package.json` to make this importable via your CDN?

I'm happy to send a PR to snabbdom to help move things along after I understand the issue.

thanks for an _amazing_ service btw! ❤️

**Comment by drwpow** [comment]
Hey @mreinstein! Thanks so much for the love!

I believe the issue is that there’s neither a main entry via an `"exports": { ".": ` entry ([docs](https://nodejs.org/api/packages.html#packages_subpath_exports)) nor a top-level `"main"` entry in the package.json.

If this is intentional, e.g. users must always import `snabbdom/init` or `snabbdom/h` and never `snabbdom`, then we might have a bug in Skypack. But if you do want to expose a main entry for your package, then add a `.` key to `exports` pointing to it.

**Comment by mreinstein** [comment]
ahhh ok that makes sense. So basically snabbdom seems to be designed not to have a top level entry point, it's currently just a piecemeal collection of modules. I'll see if I can propose changes to snabbdom to alleviate this.

Thanks for digging in!

**Comment by drwpow** [comment]
> So basically snabbdom seems to be designed not to have a top level entry point, it's currently just a piecemeal collection of modules

Got it. You know, there‘s technically nothing preventing npm modules from doing this! So to your point we should definitely support this better. The main entry should be a workaround for now, but our goal is to defer to library authors’ intent as much as possible; we don’t want to place restrictions on how you ship your code. I’ll update you here when we support the no-main-entry story a bit better.

**Comment by mreinstein** [comment]
It makes sense to me that nothing is wrong with the package per-se. I guess just from my perspective almost everyone that is going to try to integrate a module would try `import pkg from '<CDN>/<packagename>'` so it might make sense to at least have that use case functioning "out of the box". I'm planning to suggest that if it hasn't already been done.

**Comment by drwpow** [comment]
> I guess just from my perspective almost everyone that is going to try to integrate a module would try `import pkg from '<CDN>/<packagename>'`

Right, and the vast majority of packages do have a default import. So it‘s not just Skypack—even with a local build tool and npm this means you couldn’t use `import pkg from 'snabbdom'` either, which is what a lot of users expect. You’d always have to use `import pkg from 'snabdom/[subpath]'` every time. It’s fine; both work the same. But I think this is the first package I’ve encountered that truly has no main entry, and it’s pretty unique in that regard, even if the package itself is valid.

Edit: and the reason this fails in Skypack is because we do a ton of optimizations for packages so they can not only _work_ on the web but _load quickly_ and that expectation of a main entry is where this is failing—we fail at the optimize step that runs before you even load the package.

**Comment by matthewp** [comment]
We are adding support in esinstall for packages that only have an `exports` field and no `main`. This includes packages like this which are intended to only import subpaths. However you still won't be able to import `snabbdom` since that is the author's inetnt.

**Comment by mreinstein** [comment]
@matthewp  that's changing soon, with new maintainership. see https://github.com/snabbdom/snabbdom/issues/913

**Comment by matthewp** [comment]
Perfect! In that case it should start working without a subpath in Skypack.
