### ISSUE TITLE
Support subresource integrity (SRI)

### ISSUE THREAD

**Issue by aral** [pikapkg/cdn#135]
As per @melissamcewen’s advice, opening an issue on this here.

Link to original discussion on Snowpack: https://github.com/snowpackjs/snowpack/discussions/2569

**Comment by FredKSchott** [comment]
Hey @aral! Subresource integrity support is unfortunately missing from the ESM spec. Since this is a missing browser feature, there's not much that we can do to support this until browsers add support.

For what it's worth, I know people are working on this in the browsers, and the new "import assertions" spec may be an onramp for browsers to add SRI support to each import. As soon as its added, we'll do whatever needed to support it.

**Comment by aral** [comment]
@FredKSchott Wow, I didn’t realise it was missing from the spec. Will update the post to reflect this. I’m flummoxed how that happened.

In my quick spike here https://github.com/small-tech/subresource-integrity-spike I found the following:

  - When subresource integrity is specified on a script tag, it is also blocked in a subsequent import attempt from a separate script tag in Gecko and Blink but not in WebKit (at least with the version in Epiphany. Not tested with Safari.)

Assuming this is non-standard behaviour then?

Will keep looking into this and report back if I find anything more.

**Comment by FredKSchott** [comment]
I'm not sure actually, but my guess is that its undefined in the spec.
