### ISSUE TITLE
bson.d.ts importing /error/buffer?from=bson

### ISSUE THREAD

**Issue by dn1t** [pikapkg/cdn#138]
I'm using the bson module, but [bson.d.ts](https://cdn.skypack.dev/-/bson@v4.2.2-kgdFkBIpILByFdPjvZHZ/dist=es2020,mode=types/bson.d.ts) is importing `import { Buffer } from '/error/buffer?from=bson';`

**Comment by drwpow** [comment]
This is a tricky one, and something we need to improve support on. The issue is that BSON is importing from Node’s built-in `buffer` library, which has no type definitions on its own. So it’s assuming a type definition provided by `@types/node`, a third-party package. We aren’t making the connection to the DefinitelyTyped third-party package.

Might I ask if you’re trying to load this in a browser? Or in Deno? If in a browser, this won’t work anyway because `buffer` won’t work. But in Deno, where should those types be loaded from? Would aliasing to `deno.land/std/node/buffer` work as expected?
