### ISSUE TITLE
[Feature] Deep Package Imports

### ISSUE THREAD

**Issue by NMinhNguyen** [pikapkg/cdn#14]
I seem to be unable to load `@material-ui/core/Button` (which is the preferred way to import Material-UI components, see https://material-ui.com/guides/minimizing-bundle-size/#option-1):

```js
const script = document.createElement('script');
script.type = 'module';
script.src = 'https://cdn.pika.dev/@material-ui/core/Button@%5E4.10.1';
document.head.appendChild(script);
```

![image](https://user-images.githubusercontent.com/2852660/83892301-5db65080-a746-11ea-8671-b13746cb9561.png)

Importing from `@material-ui/core` isn't recommended because it can pull in way too much code.

**Comment by FredKSchott** [comment]
Importing from files within a package is still experimental, and only well supported for a couple of packages (svelte, preact).

We'll be adding this support soon though, stay tuned

**Comment by georges-gomes** [comment]
Hi @FredKSchott 

We added support for Pika CDN as dependency manager https://webcomponents.dev and https://components.studio

<img width="491" alt="Screenshot 2020-06-22 at 08 19 30" src="https://user-images.githubusercontent.com/5250572/85258787-51c9ce80-b468-11ea-9ac7-0d5e66a774fb.png">

It works pretty well 👍 but in our case deep imports are pretty common.

Just coining a vote for the feature here.

**Comment by FredKSchott** [comment]
Update: Support has been added! Still considered experimental over the next couple of weeks, but it currently works for all known cases.

**Comment by FredKSchott** [comment]
Note that `https://cdn.pika.dev/@material-ui/core/Button@%5E4.10.1` isn't the correct URL, that would be `https://cdn.pika.dev/@material-ui/core@^4.10.1/Button`.

Also, worth noting that exports currently only support packages published as ESM. Since @material-ui is CJS, this package still only works from the main entrypoint (for now)

**Comment by NMinhNguyen** [comment]
Ah thanks.

> Since @material-ui is CJS

It's actually not. Check `module` field in https://unpkg.com/browse/@material-ui/core@4.10.0/Button/package.json

**Comment by NMinhNguyen** [comment]
That being said if I hit `esm/Button` directly (presumably, `pika.dev` doesn't use `package.json` in module resolution), then https://cdn.pika.dev/@material-ui/core/esm/Button and then https://cdn.pika.dev/-/@material-ui/core@v4.10.2-HfV8Hzq1BKBjNDu13I4k/dist=es2019,mode=exports/esm/Button seems to show that there's no bundling? This would lead to a waterfall:

```js
// https://cdn.pika.dev/-/@material-ui/core@v4.10.2-HfV8Hzq1BKBjNDu13I4k/dist=es2019,mode=exports/esm/Button/index.js
export { default } from './Button';
```

**Comment by FredKSchott** [comment]
Yup, right now importing a file directly causes the CDN to flip to unbundled code because of that exact issue. We can remove the waterfall by sending the proper `modulepreload` headers down to the browser, but you're still left with ~100 requests just for that one Button. 

There are two options to resolve:
1. Import the entire package at once. It's probably larger than you need, but it's optimize to have no request waterfall. 
2. If a package has an "exports" map configured, we can pre-bundle based on that. That would give you exactly what you want (minimal requests, minimal file size) but it's something that the package authors will need to configure.

**Comment by FredKSchott** [comment]
This has been completed! We now pre-bundle and optimize assets based on an export map if one exists. If one does not exist, then we serve the resources directly out of the package.

If you're looking to use a package that is ESM and has no export map, consider asking the team to add one. Or, if they don't want to, you can create one in this project: https://github.com/pikapkg/DefinitelyExported

DefinitelyExported will be our project for crowd-sourced export maps (a lot like DefinitelyTyped is for TypeScript types) that we'll plug into internally.
