### ISSUE TITLE
[Package Error] monaco-editor@0.24.0 is broken

### ISSUE THREAD

**Issue by kurtcodemander** [pikapkg/cdn#173]
monaco-editor 0.24.0 (the current default) is broken. 

Broken: 

https://cdn.skypack.dev/monaco-editor
https://cdn.skypack.dev/monaco-editor@0.24.0

Works: 

https://cdn.skypack.dev/monaco-editor@0.23.0

Actual problem with 0.24.0: 

This URL returns 500 internal server error: 

https://cdn.skypack.dev/-/monaco-editor@v0.24.0-PnrYpWw8NBzHIMPv4NIM/dist=es2020,mode=imports/optimized/common/editor.main-fb7d68f0.js

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: arn1::77znb-1621534396693-7d4e1444262f

**Comment by drwpow** [comment]
Thanks for raising. Unfortunately we’ve been experiencing interruptions in our development URLs due to an ongoing issue with Cloudflare and Vercel. The problem is intermittent, and Vercel is currently working on a fix.

We recommend using our **production URLs** (pinned URLs) for reliability. The pinned URLs do not currently have this issue as far as we know (they are backed by Cloudflare’s edge CDN whereas development URLs are not)

**Comment by kurtcodemander** [comment]
Thanks, pinned version works.

**Comment by kurtcodemander** [comment]
The minified pinned url doesn't seem to work. The normal pinned url works fine. 

https://cdn.skypack.dev/pin/monaco-editor@v0.24.0-PnrYpWw8NBzHIMPv4NIM/mode=imports,min/optimized/monaco-editor.js

Because the following import gives "500 internal server error": 

https://cdn.skypack.dev/-/monaco-editor@v0.24.0-PnrYpWw8NBzHIMPv4NIM/dist=es2020,mode=imports,min/optimized/common/editor.main-fb7d68f0.js

**Comment by kurtcodemander** [comment]
It works again.
