### ISSUE TITLE
three@v0.133.0  could not be built

### ISSUE THREAD

**Issue by grzesiekmq** [pikapkg/cdn#226]
[Package Error] "three@v0.133.0" could not be built.

**Comment by FredKSchott** [comment]
Looking into this now, seems like a caching issue at our CDN

**Comment by gingershaped** [comment]
Nominated for the Melted the Internet award

**Comment by ycw** [comment]
> 
> 
> Looking into this now, seems like a caching issue at our CDN

would it be great if threejs provides `exports` field in package.json? @FredKSchott

**Comment by FredKSchott** [comment]
Fixed! Issue was a race condition on npm that we weren't handling: when 0.133.0 was released, npm began resolving to the new version before it was actually available for download. We failed to download the package (404 from npm) and then cached that result into our DB. We will add handling for temporary errors like this so that this sort of error isn't treated as permanent in the future.

Apologies for the disruption everyone! This is a good reminder to use production Pinned URLs if you use Skypack in production, which are an essentially static code path vs. the dynamic lookup that you're doing every time your users hit `/three`. Link to the docs is on the homepage: https://www.skypack.dev/
