### ISSUE TITLE
Error 520: Header Overflow Issue

### ISSUE THREAD

**Issue by coryrylan** [pikapkg/cdn#32]
I was attempting to import from the `@clr/core` package. It looks like most of the imports work without issue with the exception of this import 

```js
import { userIcon } from 'https://cdn.skypack.dev/@clr/core@4.0.0-rc.1/icon'; // fails

import { userIcon } from 'https://cdn.skypack.dev/@clr/core@4.0.0-rc.1/icon/shapes/user.js'; // deep import works without issue
```

This file does re-export a large amount of other files. This is our design systems icons package. I can reach each icon file independently without issue. I'm not sure if maybe I am doing something wrong or causing a performance bottleneck.
Thank you!

**Comment by FredKSchott** [comment]
Thanks for filing! It looks like the number of imports in this file causes a header overflow, since we include that full list as a header in a too verbose format. 

Cleaned up the header to be more concise, which will support as many imports as you need and then some, without overflowing. Will ping this thread once we get that released.

**Comment by drwpow** [comment]
We just deployed an update to the CDN which fixes the issue. I’m seeing `https://cdn.skypack.dev/@clr/core@4.0.0-rc.1/icon` pass now!

However, it seems like we’re not properly preloading the deep dependencies here, which is causing a waterfall issue. So this is working, but could be optimized a little further.

**Comment by FredKSchott** [comment]
@drwpow it looks like it may have just cached the old, "bad" result that came back empty. We can try to clear out the cache and confirm.

**Comment by FredKSchott** [comment]
yup, looks like all those imports are still causing issues in our preload waterfall handling. There are so many of them!

**Comment by stramel** [comment]
@FredKSchott Can we send up to X amount then break the rest into Y chunks of "preload files"?

**Comment by drwpow** [comment]
After thinking about this a bit, and wrestling with related issues, I think that this waterfall problem must be solved by the package. Ideally this happens with the [`"exports"`](https://nodejs.org/api/packages.html#packages_subpath_exports) field in `package.json`.

The reason is that when it imports individual files (what we call “raw files”), we serve the file as-intended. This is ideal behavior for non-JS files & assets (CSS, images, wasm), but with JS it becomes hard to truly optimize until you know where the “entry” is for a given import chain (optimizing somewhere in the middle has problems—you either end up with too much bundling and thus duplication between imports, or too little and you get this waterfall problem here).

We think the best way to solve this is with [export maps](https://nodejs.org/api/packages.html#packages_subpath_exports) which serve as a package’s designated entry points. Since `@clr/core` doesn’t take advantage of this, it’s hard for us to optimize properly, and the waterfall happens. However, if this package added that (as well as ideally its dependencies), Skypack can do a much better job of optimizing the waterfall ahead-of-time.

**Comment by coryrylan** [comment]
@drwpow @FredKSchott  thank you for taking the time to look into this. Agree with the waterfall problem being a package optimization. Already working on improving this and documentation for our users. Thanks for posting the link about the submodule metadata! Hoping to fix this on our end in our next release. Going to close the issue since this looks like something we need to handle on our side. (feel free to reopen if needed)
