### ISSUE TITLE
[Feature] support devDependencies for package resolution

### ISSUE THREAD

**Issue by drwpow** [pikapkg/cdn#45]
Try loading `antd` via Skypack:

```js
import('https://cdn.skypack.dev/antd');
```

You’ll get the following error:

```
Uncaught (in promise) Error: [Package Error] "react-dom" no dependency version info found. (Imported by "rc-util").
```

That’s caused by an error in [this file](https://cdn.skypack.dev/-/rc-util@v5.0.7-QFhasXqIMxQwdFL9UHuI/dist=es2020,mode=raw/es/Dom/addEventListener.js):

```js
import "/error/unknown:react-dom?from=rc-util"; /* Skypack: Broken imports removed */;
```

It looks like `rc-util` only includes `react` and `react-dom` as `devDependencies` rather than `dependencies` or `peerDependencies`. While this seems like an error on behalf of the package maintainer, it doesn’t feel right that we should punish the user for it. Should we add `devDependencies` to our package resolvers?

**Comment by JayaKrishnaNamburu** [comment]
Hi @drwpow just to add a little more context, `jspm` fallbacks to the latest version of the package, if user misses out the dependency in `package.json`. Just drooping here as it could help for some inspiration or ideas for discussion.

https://github.com/jspm/project/issues/76#issuecomment-679984759

**Comment by FredKSchott** [comment]
I'm actually going to push back on this, for a couple of reasons: 

- One is implementation: we end up resolving all packages ahead of time (from semver to correct version), so adding dev dependencies to the list of dependencies that we resolve dramatically slows down our resolution time. This is something that we could probably address separately, but it is the reason we removed this functionality that previously existed.
- The other is that it's buggy: I wish I remember the name of the package, but what triggered the change to not "default to latest" was that a package that defaulted to latest was actually built for an older version, and so the code failed to run. This was interpreted by the user as a bug in Skypack, when really it was a bug in the package. I know that's not the exact issue here, but it's the other possible fix.

We do plenty of things that correct mistakes in bad packages, but in this case we can't do it with 100% accuracy and when we fail to correct the mistake the result is worse. Because this is a blatent miss on the shoulders of the package author (with an easy fix that would benefit all) I'm fine taking a stand here and hopefully getting these packages fixed sooner rather than later.

/cc @guybedford happy to do some digging and find that package that broke on `"default to latest"` if you're curious.
