### ISSUE TITLE
Miscellaneous problems

### ISSUE THREAD

**Issue by bgub** [pikapkg/cdn#47]
Cool project! Here are a few quick problems I have:

- Visiting https://www.skypack.dev/npm/eta results in an infinitely loading wheel.
- Visiting https://www.skypack.dev/npm/squirrelly returns a very old version of Squirrelly (`7.9.2`, while the current is `8.0.5`)

**Comment by bgub** [comment]
My packages both use `fs` and `path` in the CommonJS version (which is pointed to by `main` in my `package.json`.

I have it set up so JSDelivr and Unpkg correctly serve the browser versions -- is there a way to do that with Skypack?

**Comment by FredKSchott** [comment]
Thanks! We're doing some work on the package catalog now, and will be sure to dig into this API to see what's going on.

No special keys supported on our end, we intentionally want to work on all well-defined packages. We always prioritize "module" over "browser", but this has always been a bit tricky since no one can agree on whether "module" should be for Node ESM or Browser ESM. 

Luckily, export maps seem to be the answer: https://nodejs.org/api/esm.html#esm_package_entry_points. For a package like eta, that would be:

```
"main": "dist/eta.cjs.js",
"exports": {
  "import": "dist/eta.es.js",
  "require": "dist/eta.cjs.js",
  "browser": "dist/browser/eta.min.js"
}
```

Skypack & Snowpack both support export maps, and will prioritize "browser" over "import" or "require".

**Comment by bgub** [comment]
@FredKSchott hmm... the error is still happening though I added export maps (http://unpkg.com/eta/package.json).
