### ISSUE TITLE
Does not detect readme.md (not uppercase)

### ISSUE THREAD

**Issue by fregante** [pikapkg/cdn#69]
This package visibly has a readme file: https://www.skypack.dev/view/github-url-detection

But skypack.dev doesn't detect it

<img width="779" alt="Screen Shot 2020-11-10 at 10 33 01" src="https://user-images.githubusercontent.com/1402241/98702564-20cb3700-2340-11eb-99e3-f1440a9bb25b.png">

GitHub supports a variety of readme formats, so SkyPack should be more lenient here (or at the very least _not case sensitive_)

npm also supports _any extension_ when looking for a readme:

https://github.com/npm/read-package-json/blob/10175d86f7f5dacb219f438298bf13cf388f1d98/read-json.js#L241

**Comment by drwpow** [comment]
Really sorry about that! What I think happened is that we update these checks on every update to your package. And my guess is that we tried to update the README and it failed (network timeout or something). So the check failed, but we still had the previous README version cached which is why it displayed.

We have an improvement to the package checks planned where this gets refreshed when you visit this URL, so there’s less of a chance that we have stale checks laying around. At any rate, this has been fixed for this package specifically, and I’ll look into preventing this from happening in the future.

Thanks for filing!

**Comment by astoilkov** [comment]
Same here: https://www.skypack.dev/view/use-local-storage-state.

I don't know if you fixed this but I just saw it as well. Just to give you one more example if you are still struggling with this.
