### ISSUE TITLE
No "exports" main error

### ISSUE THREAD

**Issue by bahrus** [pikapkg/cdn#89]
I've tried to start using the "exports" field in package.json.  Documentation is a bit sparse, I'm finding, in how to use the field properly.  Or at any rate, I find myself guessing, and it may be causing issues with Skypack.

Demo is [here](https://jsfiddle.net/bahrus/2h1mdbpv/1/)

Using the network tab of chrome dev tools, the full error is:

```JavaScript
console.warn("[Package Error] \"xtal-sip\" could not be built. (Imported by \"xtal-sip\").\nInstalling package...\nNo \"exports\" main defined in xtal-sip/package.json\nNo \"exports\" main defined in /tmp/cdn/_ewKQNIdf2edyapO9u0VP/node_modules/xtal-sip/package.json");
throw new Error("[Package Error] \"xtal-sip\" could not be built. (Imported by \"xtal-sip\").");
export default null;
```

The package.json file can be found [here](https://github.com/bahrus/xtal-sip/blob/baseline/package.json)

```JSON
  "exports": {
    "conditionalImport.js": {
      "import": "./conditionalImport.js"
    },
    "preemptiveImport.js": {
      "import": "./preemptiveImport.js"
    }
  }
```

I have two ES6 Module files at the root level with names conditionalImport.js and preemptiveImport.js

A quick search of that error indicates this is a babel error, but I'm not clear if I'm doing something wrong, or if this is just something SkyPack doesn't support yet (which seems unlikely)?

Thanks in advanced for any help you can provide.

**Comment by drwpow** [comment]
Hey bahrus! Yes we strongly encourage using `exports` for Skypack. And I agree there’s not much info on it yet. The best resource so far is the [official Node.js docs](https://nodejs.org/api/packages.html#packages_package_entry_points).

There’s a syntax error in your export map. It should look more like this:

```json
  "exports": {
    ".": {
      "browser": "./conditionalImport.js"
    },
    "./conditionalImport.js": {
      "browser": "./conditionalImport.js"
    },
    "./preemptiveImport.js": {
      "browser": "./conditionalImport.js"
    }
  }
```

Namely:

1. You should always have a `.` entry in exports: this is what gets imported when someone runs `import xtalSip from 'xtal-sip';`.
2. Every top-evel entry in `"exports"` should always start with `./`.
3. I’d recommend using `browser` over `import` (the former is more meant to be for browsers; the latter is more meant to be ESM running in Node)

Also, if you are only making a package for browsers only, and don’t need to load anything in Node, you can also shorten it. This is also valid:

```json
  "exports": {
    ".": "./conditionalImport.js",
    "./conditionalImport.js": "./conditionalImport.js",
    "./preemptiveImport.js": "./conditionalImport.js"
  }
```

**Comment by drwpow** [comment]
But that said, even though we recommend using export maps in Skypack, we’re still working on more clear error messages when something is invalid, and we’re still working on some more advanced features of export maps such as [wildcard imports (`./*`)](https://nodejs.org/api/packages.html#packages_package_entry_points). But we will have all that within the next couple weeks; stay tuned!

**Comment by bahrus** [comment]
Hi @drwpow 

Thanks for the helpful feedback.  I tried what you suggested.

I'm now seeing an extra "js" being added to the path.  File https://cdn.skypack.dev/-/xtal-sip@v0.0.116-QLiiXv0RSfiGS6fZFqc8/dist=es2020/xtal-sip/preemptiveImportjs.js is being requested.  I *think* this might be a skypack bug?

Demo [here](https://jsfiddle.net/bahrus/2h1mdbpv/4/)

xtal-timeline is [referencing preemptiveImport.js](https://github.com/bahrus/xtal-timeline/blob/master/xtal-timeline.js), not preemptiveImportjs.js

**Comment by drwpow** [comment]
Ah yes, you’re right. That is a bug in our handling! I will track that issue. You’re right—that code should work as-is on Skypack.

**Comment by drwpow** [comment]
Dug in a little more, and here’s the current behavior, which is `404`ing as you said:

![Screen Shot 2020-12-11 at 19 07 22](https://user-images.githubusercontent.com/1369770/101969870-2dafa480-3be4-11eb-8307-9918409a3724.png)

I was able to fix the resolution bug in our staging CDN, and I’m seeing a different response now (progress, I guess)?:

![Screen Shot 2020-12-11 at 19 08 33](https://user-images.githubusercontent.com/1369770/101969887-491aaf80-3be4-11eb-87a8-2a0f370325d6.png)

So I _think_ this is expected. Because in your export map, you have `"./preemptiveImport.js": "./conditionalImport.js"`. If you look at [conditionalImport.js](https://github.com/bahrus/xtal-sip/blob/baseline/conditionalImport.js), you’ll see that `preemptiveImport` **is NOT exported**. However, if you added `export preemptiveImport` to that file, it _should_ resolve (it’s hard for me to confirm without publishing a package to npm myself).

Hopefully this fixes the issue! Again, this is still on staging, not production, so we could push this sometime next week (after we run our usual tests).

**Comment by bahrus** [comment]
I corrected the export value to be what I *think* it should be (I didn't examine the suggestion carefully enough when I copied and pasted it).  I.e. the JSON below makes sense to me:

```JSON
  "exports": {
    ".": "./conditionalImport.js",
    "./conditionalImport.js": "./conditionalImport.js",
    "./preemptiveImport.js": "./preemptiveImport.js"
  }
```

conditionalImport.js does reference preemptiveImport.js, but I want preemptiveImport.js to be usable, standalone, without importing an export symbol from conditionalImport.

But I'm still getting the extra js, probably because your fix is still in the staging area.

If my mental model of the exports JSON is still not quite right, and even in my desired scenario, I need to really have
"./preemptiveImport.js": "./conditionalImport.js"

and add the export of preemptiveImport.js, I'm happy to try that, let me know.

**Comment by drwpow** [comment]
<img width="816" alt="Screen Shot 2020-12-12 at 10 30 56" src="https://user-images.githubusercontent.com/1369770/101990628-2381ba80-3c65-11eb-92d7-b4c612ac529c.png">

Yup! Your update is working for me now on our staging CDN. We’ll have to run our test suite before deploying, but we can deploy the fix in the next week.

To your question about export maps, this is how I think about it; maybe it will help. Much like in JS a class can have private methods, there are many parts of your app that you don’t want external things to access. For your library, there may be many things you `export` from a module, but you still probably want to keep most of those private to external things. Before export maps, everything was public—anything `export`ed is “public” even if you didn’t mean for it to be. But when you add an export map, it makes everything “private” by default, and you pick the files that an external service can use. It should be noted that export maps don’t restrict your own code; you can still import/export everything internally you need to. The export map only restricts external apps using your code.

To me, export maps just make it clearer how your library is meant to be used. You can also add some quality of life improvements, too, like if your library exports a button, you can add `"./button": "./dist/esm/button/index.js"`, so users only have to type `my-module/button` instead of the much longer path. Again, you’re only declaring the external interface.

Hopefully that’s a helpful way to think about it! I think it adds a whole new utility layer to JS.

**Comment by drwpow** [comment]
Update: we’ve deployed the new version to the CDN! I’m going to close this as the original issue is now fixed. I’m seeing a new error that‘s consistent with my message above. Hopefully this unblocks you!
