### ISSUE TITLE
How to self-referencing in the library

### ISSUE THREAD

**Issue by mantou132** [pikapkg/cdn#92]
Use `import('https://cdn.skypack.dev/lit-html')` to import `lit-html`

This will import all the contents of the [lib](https://github.com/Polymer/lit-html/tree/master/src/lib) directory.

When I import other [directive](https://github.com/Polymer/lit-html/tree/master/src/directives) of `lit-html`, the contents of the `lib` directory will be re-imported:

```
import('https://cdn.skypack.dev/lit-html/directives/repeat')
```

How to fix this problem and avoid importing the same content repeatedly?

**Comment by drwpow** [comment]
That sounds like ES modules are working correctly! You should see the same modules being reimported. But in your network panel, revisiting the same module again is already **cached.** It’s just like any network resource—once downloaded, it’s instantly available.

Unless you’re seeing cache misses on the same resource? Then that would be a problem.

**Comment by mantou132** [comment]
When I import `lit-html`, what actually loads is a packaged file, which includes all files in `lib`:
<img width="1115" alt="Screen Shot 2020-12-19 at 2 40 25 PM" src="https://user-images.githubusercontent.com/3841872/102682935-2736b380-4208-11eb-9845-38afbd361da3.png">

When I import a lit-html `directive`, the modules in the lib directory will be imported separately.

<img width="1169" alt="Screen Shot 2020-12-19 at 2 42 22 PM" src="https://user-images.githubusercontent.com/3841872/102682981-7b419800-4208-11eb-94fc-ac29378f1236.png">

It seems that the only solution is not to package the lib directory

**Comment by drwpow** [comment]
Ah I understand now. Yes, I agree that is unexpected.

This is actually the same issue as #44, where `lit-html` isn’t optimizing well on Skypack. We’re in the process of fixing this by adding a better story for `lit-html`.

The short version is that for the vast majority of packages, they do not ship optimized code for browsers. We have to do our best guess to reduce the number of total requests needed to load a package; otherwise Skypack isn’t viable for people. But for `lit-html`, our best “guess” isn’t perfect, as you’ve pointed out.

The improvement to `lit-html` here will take a bigger change to our CDN, but one we’re working on now, and hope to have live soon.

**Comment by drwpow** [comment]
So update: we have made progress on this! It’s in-the-ready for release, but we want to do a little more testing before it goes live (hopefully early next year). Because I’m pretty confident this is captured in #44, I’m going to close this ticket but keep that one open. Please follow that thread for updates.
